name: Pytest Flisol 2020

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v --cov --html=reporte/pytest.html
    - name: Subir reporte pytest
      uses: actions/upload-artifact@v1
      with:
          os: ubuntu-latest
          python-version: 3.7
          name: pytest-coverage-report
          path: reporte/
